### PR TITLE
fix(cli): supplied options were being overridden with default values

### LINKED ISSUE #3263: CLI does not generate correct font and border-radius tokens from config or options
### Version number

0.0.0-next-20250228092532

### Description of the bug

Found when testing to update community figma file in https://github.com/designsystemet/Figma-community-template

When using this border-radius and font-family is not defined correctly in outputted tokens.

### Steps To Reproduce

Use following config file 

```json
    "themes": {
        "etat1": {
            "colors": {
                "main": {
                    "primary": "#0062BA",
                    "accent": "#1E98F5"
                },
                "support": {
                    "extra1": "#F45F63",
                    "extra2": "#E5AA20"
                },
                "neutral": "#1E2B3C"
            },
            "borderRadius": 4,
            "typography": {
                "fontFamily": "Inter"
            }
        },
        "etat2": {
            "colors": {
                "main": {
                    "primary": "#2D6A4F",
                    "accent": "#EADBC8"
                },
                "support": {
                    "extra1": "#76203F",
                    "extra2": "#466D86"
                },
                "neutral": "#1E2B3C"
            },
            "borderRadius": 9999,
            "typography": {
                "fontFamily": "Open Sans"
            }
        }
    }
```

### Additional Information

~~Typography token `extra-bold` has wrong value. Should be `SemiBold` according to Token Studio~~
edit: Fixed in #3264 
```

### PR DESCRIPTION
**Pull request by unekinn**
Closes #3263

### CODE REVIEW

File: packages/cli/bin/designsystemet.ts [hunk 1]
```diff
@@ -135,16 +135,23 @@ function makeTokenCommands() {
...
+        outDir: propsFromJson?.outDir ?? getCliOption(cmd, 'outDir'),
+        clean: propsFromJson?.clean ?? getCliOption(cmd, 'clean'),
         themes: propsFromJson?.themes
-          ? // For each theme specified in the JSON config, we override the config values
-            // with the explicitly set options from the CLI.
-            R.map((theme) => R.mergeDeepRight(theme, getThemeOptions(getDefaultOrExplicitOption)), propsFromJson.themes)
+          ? R.map((jsonThemeValues) => {
+              // For each theme specified in the JSON config, we get the options in the following order:
+              // - default values for CLI command options
+              // - options defined in
```
Comment (mimarz) [inline packages/cli/bin/designsystemet.ts:144]:
```suggestion
              // - options defined in config file
```

File: packages/cli/bin/designsystemet.ts [hunk 2]
```diff
@@ -135,16 +135,23 @@ function makeTokenCommands() {
...
+              // - explicitly set CLI command options
+              // With later values overriding earlier values
```
Comment (mimarz) [inline packages/cli/bin/designsystemet.ts:146]:
```suggestion
              // For each theme specified in the JSON config, we resolve the option values in the following order:
              // - default value
              // - config value
              // - CLI value
              // With later values overriding earlier values
```

**Review by mimarz — APPROVED** [review]
Looks good. Kids are home gotta run!
