### PR TITLE
fix(Pagination): api alignment

### LINKED ISSUE #2283: Streamline how to use `Pagination` in code
Feedback that its confusing how to use the `Pagination` component. Do users use the `currentPages` & `totalPages` props or `Pagination.Root` with `usePagination` hook.

Suggest we remove the "does all for you" approach as its more limited in terms of accessibility, i18n, SSR and composability, with things like item, prev, next button etc.

Remove the single component use: 
```jsx
<Pagination
  currentPage={1}
  totalPages={10}
  onChange={setCurrentPage}
  nextLabel='Neste'
  previousLabel='Forrige'
  itemLabel={(num) => `Side ${num}`}
/>;
```

We want to prefer composable use: 

```tsx
 const { pages, currentPage } = usePagination({
    currentPage: 2,
    totalPages,
  });
```

```tsx
<Pagination.Root>
  <Pagination.Content>
    <Pagination.Item>
      <Pagination.Previous>
        <ChevronLeftIcon aria-hidden />
        Forrige
      </Pagination.Previous>
    </Pagination.Item>

    <Pagination.Item>
      <Pagination.Button isActive>1</Pagination.Button>
    </Pagination.Item>

    <Pagination.Item>
      <Pagination.Next>
        Neste
        <ChevronRightIcon aria-hidden />
      </Pagination.Next>
    </Pagination.Item>
  </Pagination.Content>
</Pagination.Root>
```

### PR DESCRIPTION
**Pull request by eirikbacker**
Fixes #2283

### CODE REVIEW

File: packages/react/src/components/Pagination/usePagination.ts [hunk 1]
```diff
@@ -1,103 +1,57 @@
...
-};
+  showPages = 7,
+}: UsePaginationProps) =>
+  useMemo(() => {
+    return {
+      /** Number of steps */
+      pages: getSteps(currentPage, totalPages, showPages).map(
+        (page, index) => ({
+          page: page || '',
+          itemKey: page ? `page-${page}` : `ellipsis-${index}`, // React key utility
```
Comment (Barsnes) [inline packages/react/src/components/Pagination/usePagination.ts:36]: We could just call this `key`, and add it `buttonProps`?

Comment (eirikbacker) [reply packages/react/src/components/Pagination/usePagination.ts:36]: unfortunately no as the `key` must be added to the Pagination.Item - the outermost element in the loop

Comment (Barsnes) [reply packages/react/src/components/Pagination/usePagination.ts:36]: Right my bad, did not see that we added they key to the `*.Item`

File: packages/react/src/components/Pagination/Pagination.mdx [hunk 2]
```diff
@@ -23,49 +23,48 @@ Vær oppmerksom på:
...
         Forrige
-      </Pagination.Previous>
+      </Pagination.Button>
     </Pagination.Item>
-
-    <Pagination.Item>
-      <Pagination.Button isActive>1</Pagination.Button>
-    </Pagination.Item>
-
+    {pages.map(({ page, itemKey, buttonProps }) => (
```
Comment (eirikbacker) [inline packages/react/src/components/Pagination/Pagination.mdx:50]: Should we rater call it `items`? as this aligns with `Pagination.Item`? :)

File: packages/react/src/components/Pagination/usePagination.ts [hunk 3]
```diff
@@ -1,103 +1,57 @@
...
-  PaginationProps,
-  'compact' | 'totalPages'
-> &
-  Partial<Pick<PaginationProps, 'currentPage'>>;
+export type UsePaginationProps = {
+  currentPage: number;
+  setCurrentPage: Dispatch<SetStateAction<number>>;
+  totalPages: number;
+  showPages?: number;
+};
```
Comment (Barsnes) [inline packages/react/src/components/Pagination/usePagination.ts:21]: Should we give the possibility to add a function to `goNext` and `goPrev`, that is called after pagination, here?

Comment (Barsnes) [reply packages/react/src/components/Pagination/usePagination.ts:21]: Or a generic `onNavigate` callback that gives old and current page?

Comment (eirikbacker) [reply packages/react/src/components/Pagination/usePagination.ts:21]: yeah, a `onChange` or `onNavigate` would be nice 🙌 the `goNext` `goPrevious` is generated by `usePagination` now and I think this makes sense, though, I have been thinking, maybe we should remove `goNext`, `goPrevious` and instead return `nextButtonProps` and `previousButtonProps` so it can be spread on the respective buttons, aligning with the `buttonProps` api? We should still return `hasNext` and `hasPrevious` still though as these can be handy ☺️

Comment (Barsnes) [reply packages/react/src/components/Pagination/usePagination.ts:21]: That sounds like a nice API! *
Not sure wether `onChange` or `onNavigate` makes sense here 🤔 As long as we provide an `on*` callback, we should be good at least 😸

File: packages/react/src/components/Pagination/Pagination.mdx (hunk 2 above)
Comment (Barsnes) [reply packages/react/src/components/Pagination/Pagination.mdx:50]: I'm not sure, not all items are in this, since prev/next buttons are outside the map.. I think pages is fine here personally

File: packages/react/src/components/Pagination/Pagination.mdx
Comment (Barsnes) [inline packages/react/src/components/Pagination/Pagination.mdx:1]: We need to document `usePagination` better.
I suggest adding a section about the hook

File: packages/react/src/components/Pagination/Pagination.stories.tsx [hunk 4]
```diff
@@ -1,127 +1,100 @@
...
-    currentPage,
-    setCurrentPage,
-    nextPage,
-    previousPage,
-    showNextPage,
-    showPreviousPage,
-  } = usePagination({
-    currentPage: 4,
-    totalPages,
+export const Preview: StoryFn<UsePaginationProps> = (args) => {
```
Comment (Barsnes) [inline packages/react/src/components/Pagination/Pagination.stories.tsx:12]: I can't use the controls here to change the `size`. 
See comment about context for a possible solution.

File: packages/react/src/components/Pagination/Pagination.tsx [hunk 5]
```diff
@@ -1,112 +1,51 @@
...
-import { PaginationButton } from './PaginationButton';
-import { PaginationEllipsis } from './PaginationEllipsis';
-import { PaginationItem } from './PaginationItem';
-import { PaginationList } from './PaginationList';
-import { PaginationNext, PaginationPrevious } from './PaginationNextPrev';
-import { PaginationRoot } from './PaginationRoot';
-import { usePagination } from './usePagination';
+export const PaginationContext = createContext({
+  size: 'md' as NonNullable<PaginationProps['size']>,
+});
```
Comment (Barsnes) [inline packages/react/src/components/Pagination/Pagination.tsx:8]: If we are using a hook for pagination, why do we need a context? Could we just add the size to the button props that is already being spread? Or simply set `data-size="*"` since we are omitting the type

File: packages/react/src/components/Pagination/usePagination.ts [hunk 6]
```diff
@@ -1,103 +1,74 @@
...
-  'compact' | 'totalPages'
-> &
-  Partial<Pick<PaginationProps, 'currentPage'>>;
+export type UsePaginationProps = {
+  currentPage: number;
+  setCurrentPage?: Dispatch<SetStateAction<number>>;
+  onChange?: (event: MouseEvent<HTMLElement>, page: number) => void;
+  totalPages: number;
+  showPages?: number;
+};
```
Comment (Barsnes) [inline packages/react/src/components/Pagination/usePagination.ts:23]: Ref to other comments, suggest adding `size` here

**Review by Barsnes — DISMISSED** [review]

File: packages/react/src/components/Pagination/usePagination.ts (hunk 6 above)
Comment (eirikbacker) [reply packages/react/src/components/Pagination/usePagination.ts:23]: Have discussed this with Micke, and will keep `size` on `Pagination` for now, as this matches the pattern of all other components, and is less error-prone than sniffing child components.

File: packages/react/src/components/Pagination/Pagination.stories.tsx (hunk 4 above)
Comment (eirikbacker) [reply packages/react/src/components/Pagination/Pagination.stories.tsx:12]: Have discussed this with Micke, and will keep `size` on `Pagination` for now, as this matches the pattern of all other components, and is less error-prone than sniffing child components.

File: packages/react/src/components/Pagination/Pagination.mdx
Comment (eirikbacker) [reply packages/react/src/components/Pagination/Pagination.mdx:1]: Agreed ☺️

Comment (eirikbacker) [reply packages/react/src/components/Pagination/Pagination.mdx:1]: Enig - har gjort et forsøk på å dokumentere, men setter veldig pris på forslag - synes det er vanskelig å vite å åssen dokumentasjonen skal se ut siden jeg ikke har jobbet så mye med det hos dere enda ☺️

**Review by Barsnes — APPROVED** [review]
🚀
