### PR TITLE
fix(Suggestion, MultiSuggestion):  no keyboard focus trap on `.List`

### LINKED ISSUE #3414: Unable to tab past Suggestion dropdown
### Version number

1.0.2

### Description of the bug

When the Suggestion input component gains focus, it opens its dropdown. While the dropdown is open, pressing `tab` does not move focus away from the dropdown. You can press `esc` to close the dropdown, but pressing `tab` opens it again

### Steps To Reproduce

1. Go to https://storybook.designsystemet.no/?path=/docs/komponenter-suggestion--docs
2. Click "Velg en destinasjon", which opens the dropdown
3. Press `tab`, notice that the focus does not move

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Barsnes**
resolves #3414

### CODE REVIEW

**Review by oddvernes — CHANGES_REQUESTED** [review]
Need to fix the same issue in MultiSuggestion as well 🙂

**Comment by eirikbacker** [comment]
This does not happen on https://u-elements.github.io/u-elements/elements/u-datalist so I'd like to research a little more before we add this to better understand the issue and why the fix works :)

File: packages/react/src/components/MultiSuggestion/MultiSuggestionList.tsx [hunk 1]
```diff
@@ -55,6 +55,7 @@ export const MultiSuggestionList = forwardRef<
       class={className} // Using "class" since React does not translate className on custom elements
       id={listId}
       ref={ref}
+      tabIndex={-1}
```
Comment (eirikbacker) [inline packages/react/src/components/MultiSuggestion/MultiSuggestionList.tsx:58]: Can instead update to `u-datalist@1.0.5` 🥳

**Review by eirikbacker — APPROVED** [review]
🙏 🥳

File: .changeset/serious-rules-grow.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+"@digdir/designsystemet-react": patch
+---
+
+**Suggestion**: Set tabindex="-1" on list, fixes keyboard focus trap
```
Comment (mimarz) [inline .changeset/serious-rules-grow.md:5]: Are these changesets correct now?

**Review by mimarz — CHANGES_REQUESTED** [review]

File: .changeset/serious-rules-grow.md (hunk 2 above)
Comment (Barsnes) [reply .changeset/serious-rules-grow.md:5]: Well they are not wrong, but it's not something we do directly anymore

Comment (mimarz) [reply .changeset/serious-rules-grow.md:5]: Maybe just the "fixes keyboard focus trap" since we didn't fix directly but its fixed by updating a dependency.

**Review by mimarz — APPROVED** [review]

**Comment by mimarz** [comment]
Diff in snapshot looks to be due to upgrade to chromatic v7 infrastructure and next being a v6 snapshot. Tested in local browser with next again PR build. Was identical.
