### PR TITLE
fix(Badge): without wrapper

### LINKED ISSUE #2341: Badge without wrapper?
Ang. spørsmål om Badge; kom på at slik Badge funker med et wrapper-element, så kan vi få problemer når noe bytte mellom å ha Badge og ikke - fordi det ikke bare er et element som legges til som barn av f.eks button, men noe som må legges rundt button. Da endrer DOMen seg ganske mye og blir potensielt ugyldig;
f.eks:
Uten badge:
```
<ul>
  <li>Tekst</li>
</ul>
```
Med bage:
```
<ul>
  <span class="ds-badge__wrapper"><li>Tekst <span class="ds-badge"></span></li></span>
</ul>
```
Skulle vi revurdert litt om vi får Badge til å uten wrapper? Vet det kommer utfordringer med det og, men bare en tanke her :relaxed:

### PR DESCRIPTION
**Pull request by eirikbacker**
Fixes #2341

### CODE REVIEW

File: packages/react/src/components/Badge/Badge.tsx [hunk 1]
```diff
@@ -64,44 +64,31 @@ const paragraphSizeMap: {
...
-          </span>
-        </Paragraph>
-      </div>
-    );
+export const Badge = forwardRef<HTMLSpanElement, BadgeProps>(function Badge(
+  {
+    className,
+    color = 'accent',
+    count,
+    maxCount = Infinity,
```
Comment (Barsnes) [inline packages/react/src/components/Badge/Badge.tsx:72]: Should also write about this default in the jsdoc

Comment (eirikbacker) [reply packages/react/src/components/Badge/Badge.tsx]: Mm, I think it will be confusing as not everyone is familiar with `Infinity` so I've instead removed the default and added a check :)

**Review by Barsnes — APPROVED** [review]
