### PR TITLE
chore: add Designsystemet video, sidebar for mobile fix

### LINKED ISSUE #3568: Add intro video using HTML <video> element + VTT
**Description:**
We want to publish a short introductory video about Designsystemet on the page [designsystemet.no/om-designsystemet](https://www.designsystemet.no/grunnleggende/introduksjon/om-designsystemet).

**Tasks:**
- [x] Add video to the page using the native HTML <video> element
- [x] Use .vtt caption files generated from Sonix for accessibility
- [x] Include English and Norwegian .vtt
- [x] Test responsiveness and mobile behavior

### PR DESCRIPTION
**Pull request by Barsnes**
resolves #3568

adds and tests vtt files:
image
image

### CODE REVIEW

File: apps/www/app/_components/sidebar/sidebar.tsx [hunk 1]
```diff
@@ -17,51 +17,66 @@ export type SidebarProps = {
...
-                  const url = `${item.url}`;
+      <Button
+        className={classes.toggleBtn}
+        data-size='md'
+        data-color='neutral'
+        variant='secondary'
+        onClick={() => setShowMenu(!showMenu)}
+        aria-expanded={showMenu}
+      >
+        {showMenu ? 'Skjul' : 'Vis'} sidemeny
```
Comment (oddvernes) [inline apps/www/app/_components/sidebar/sidebar.tsx:34]: Should this be translatable?

Comment (Barsnes) [reply apps/www/app/_components/sidebar/sidebar.tsx:34]: great catch, yes it should :)

**Review by oddvernes — APPROVED** [review]
LGTM (granted I did not review the subtitles)
